server.port: 7005
server:
  error:
    include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  databse: recommendation-db

logging:
  level:
    root: INFO
    com.kenny: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080