server.port: 7004
server:
  error:
    include-message: always

# recommend setting this to "none" for production environments
spring:
  jpa:
    hibernate:
      ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.kenny: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.profiles: docker

spring.datasource:
  url: jdbc:mysql://mysql/review-db

server.port: 8080